[lib]
name = "http_server"
path = "src/lib.rs"


[package]
name = "Xpress"
version = "0.1.0"
edition = "2021"
description = "A minimal HTTP library."
license = "MIT" 
repository = "https://github.com/MikhailWahib/xpress"
keywords = ["express", "xpress", "http"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"